# Generated by Django 6.0 on 2025-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_streak",
            field=models.IntegerField(
                default=0, help_text="Current consecutive days writing streak"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_entry_date",
            field=models.DateField(
                blank=True,
                help_text="Date of last journal entry (in user timezone)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="longest_streak",
            field=models.IntegerField(
                default=0, help_text="Longest writing streak achieved"
            ),
        ),
    ]
