# Generated by Django 6.0 on 2025-12-24 11:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_current_streak_user_last_entry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (max 2MB, 512x512px recommended)",
                null=True,
                upload_to="avatars/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Short bio about yourself", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_word_goal",
            field=models.IntegerField(
                default=750,
                help_text="Daily word count goal (100-5000 words)",
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_writing_time",
            field=models.CharField(
                choices=[
                    ("morning", "Ráno (do 12:00)"),
                    ("afternoon", "Odpoledne (12:00-18:00)"),
                    ("evening", "Večer (18:00+)"),
                    ("anytime", "Kdykoli"),
                ],
                default="morning",
                help_text="Preferred time of day for writing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reminder_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable daily writing reminders"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reminder_time",
            field=models.TimeField(
                default=datetime.time(8, 0), help_text="Time for daily reminder"
            ),
        ),
    ]
