# Generated by Django 6.0 on 2025-12-24 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_avatar_user_bio_user_daily_word_goal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(
                        help_text="The email address user wants to change to",
                        max_length=254,
                        verbose_name="New email address",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the change was requested"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this request expires (default: 24 hours)"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether the email has been verified"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When the email was verified", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting the email change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Change Request",
                "verbose_name_plural": "Email Change Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_em_user_id_d63ab4_idx",
                    ),
                    models.Index(
                        fields=["new_email", "is_verified"],
                        name="accounts_em_new_ema_c626dd_idx",
                    ),
                ],
            },
        ),
    ]
