# Generated by Django 6.0 on 2025-12-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_email_change_request_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_entry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of last journal entry (in user timezone)', null=True),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['user', 'is_verified', '-created_at'], name='accounts_em_user_id_b791a1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchangerequest',
            index=models.Index(fields=['is_verified', 'expires_at'], name='accounts_em_is_veri_8eae6e_idx'),
        ),
    ]
