# Generated by Django 6.0 on 2025-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("cs", "Čeština"), ("en", "English")],
                default="cs",
                help_text="User's preferred language",
                max_length=2,
                verbose_name="Preferovaný jazyk",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_theme",
            field=models.CharField(
                choices=[("midnight", "Midnight"), ("paper", "Paper")],
                default="midnight",
                help_text="User's preferred theme",
                max_length=10,
                verbose_name="Preferovaný motiv",
            ),
        ),
    ]
