# Generated by Django 6.0 on 2025-12-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_preferred_language_user_preferred_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has completed the onboarding process",
            ),
        ),
    ]
