# Generated by Django 6.0.1 on 2026-01-19 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_onboarding_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique token for password reset",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the reset was requested"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this token expires (default: 1 hour)"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether the token has been used"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the token was used", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting the password reset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Password Reset Token",
                "verbose_name_plural": "Password Reset Tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "is_used", "expires_at"],
                        name="accounts_pa_token_dd7ba8_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_pa_user_id_13d348_idx",
                    ),
                ],
            },
        ),
    ]
