# Generated by Django 6.0.1 on 2026-01-19 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_password_reset_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncryptionKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Fernet key (encrypted with master key)",
                        max_length=500,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Key version for rotation tracking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the active key for new encryptions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rotated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this key was last rotated",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this encryption key belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encryption_key",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Encryption Key",
                "verbose_name_plural": "Encryption Keys",
            },
        ),
    ]
