# Generated by Django 6.0.1 on 2026-01-19 22:25

from django.db import migrations
from django.core.exceptions import ImproperlyConfigured
from cryptography.fernet import Fernet


def create_keys_for_existing_users(apps, schema_editor):
    """Create EncryptionKey for all existing users who don't have one."""
    User = apps.get_model('accounts', 'User')
    EncryptionKey = apps.get_model('accounts', 'EncryptionKey')

    from django.conf import settings

    global_key = getattr(settings, 'FIELD_ENCRYPTION_KEY', None)
    if not global_key:
        raise ImproperlyConfigured(
            "FIELD_ENCRYPTION_KEY is required for migration. "
            "Please set it in your environment or settings."
        )

    if isinstance(global_key, str):
        global_key = global_key.encode('utf-8')

    master_fernet = Fernet(global_key)

    created_count = 0
    for user in User.objects.all():
        if not EncryptionKey.objects.filter(user=user).exists():
            import uuid
            raw_key = Fernet.generate_key()
            encrypted_key = master_fernet.encrypt(raw_key).decode('utf-8')
            EncryptionKey.objects.create(
                id=uuid.uuid4(),
                user=user,
                key=encrypted_key,
                version=1,
                is_active=True,
            )
            created_count += 1

    print(f"Created {created_count} encryption keys for existing users")


def reverse_migration(apps, schema_editor):
    """Remove encryption keys (data will be lost!)."""
    EncryptionKey = apps.get_model('accounts', 'EncryptionKey')
    EncryptionKey.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_encryption_key'),
    ]

    operations = [
        migrations.RunPython(
            create_keys_for_existing_users,
            reverse_migration,
        ),
    ]
