# Generated by Django 6.0.1 on 2026-01-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_create_encryption_keys_for_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referrer",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Full referrer URL when user first visited",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="utm_campaign",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Campaign name (e.g., launch-week-1)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="utm_medium",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Marketing medium (e.g., social, referral, email)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="utm_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Traffic source (e.g., reddit, twitter, hackernews)",
                max_length=100,
            ),
        ),
    ]
