# Generated by Django 6.0.1 on 2026-01-27 20:33

from django.db import migrations


def update_site_domain(apps, schema_editor):
    """Update the default Site domain to quietpage.com for OAuth."""
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(id=1)
        site.domain = 'quietpage.com'
        site.name = 'QuietPage'
        site.save()
    except Site.DoesNotExist:
        # Create site if it doesn't exist
        Site.objects.create(id=1, domain='quietpage.com', name='QuietPage')


def reverse_site_domain(apps, schema_editor):
    """Reverse migration - set back to example.com."""
    Site = apps.get_model('sites', 'Site')
    try:
        site = Site.objects.get(id=1)
        site.domain = 'example.com'
        site.name = 'example.com'
        site.save()
    except Site.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_utm_tracking_fields"),
        ("sites", "0001_initial"),  # Ensure sites app is migrated first
    ]

    operations = [
        migrations.RunPython(update_site_domain, reverse_site_domain),
    ]
