# Generated by Django 6.0.1 on 2026-01-27 20:36

from django.db import migrations


def fix_site_domain(apps, schema_editor):
    """Fix Site domain to quietpage.app (not quietpage.com)."""
    Site = apps.get_model('sites', 'Site')
    Site.objects.filter(id=1).update(domain='quietpage.app', name='QuietPage')


def reverse_site_domain(apps, schema_editor):
    """Reverse to quietpage.com."""
    Site = apps.get_model('sites', 'Site')
    Site.objects.filter(id=1).update(domain='quietpage.com', name='QuietPage')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_update_site_domain"),
    ]

    operations = [
        migrations.RunPython(fix_site_domain, reverse_site_domain),
    ]
