# Generated by Django 6.0.1 on 2026-01-27 20:39

from django.db import migrations


def fix_site_domain(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.filter(id=1).update(domain='www.quietpage.app', name='QuietPage')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_fix_site_domain_to_quietpage_app"),
    ]

    operations = [
        migrations.RunPython(fix_site_domain, migrations.RunPython.noop),
    ]
