# Generated by Django 6.0 on 2026-01-05 21:32

import apps.journal.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_add_uuid_tagged_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=apps.journal.fields.EncryptedTextField(
                blank=True, help_text="Your private journal entry (encrypted)"
            ),
        ),
    ]
