# Generated by Django 5.2.10 on 2026-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_allow_empty_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="is_favorite",
            field=models.BooleanField(
                default=False, help_text="Mark entry as favorite"
            ),
        ),
    ]
