# Generated by Django 6.0.1 on 2026-01-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_featuredentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="key_version",
            field=models.IntegerField(
                blank=True,
                help_text="Version of user's encryption key used for this entry",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Your private journal entry (encrypted with user's key)",
            ),
        ),
    ]
